plugins:
  user_network_vis_render_height:
    default: 720
    min: 500
    max: 1600
    client: true
  user_network_vis_enabled:
    type: bool
    default: true
    client: true
  user_network_vis_minimum_trust_level:
    default: 0
    max: 4
    min: 0
  user_network_vis_reply_multiplier:
    default: 2
    max: 4
    min: 1
  user_network_vis_link_score_threshold:
    default: 0
    min: 0
